version: '3'
services:
   geth:
      build: ./geth/
      # (ports should be open for debug only)
      # ports:
      #   - "8545:8545"
   db:
      image: postgres:11-alpine
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      # (ports should be open for debug only)
      # ports:
      #   - "5432:5432"
      volumes:
         - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      restart: "always"
   server:
      build: ./server/
      ports:
         - "9091:9091"
      environment:
         - PGSQL_DSN=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
         - GETH=http://geth:8545
         - GETH_MIN_CONFIRMATIONS=6
         - GETLAST_CONFIRMATIONS=3
         - HOST=0.0.0.0
         - PORT=9091
      restart: "always"
